### ISSUE TITLE
Rasm devorga tegib turishi kerak edi 

### ISSUE THREAD

**Issue by FakhriddinovSh** [SayramovAzizbek/Myteam#10]
![image](https://user-images.githubusercontent.com/94530124/177598821-2fa6c719-9bba-4873-b9ac-b07f67542ac4.png)
![image](https://user-images.githubusercontent.com/94530124/177598854-c76d03cc-093a-429e-9d49-11319eeeabb7.png)

**Comment by SayramovAzizbek** [comment]
ha buning sababi bu sal kichniaroq kompyuterda qiinganligi edi hozr bular to'g'irlanib qo'yilgan
