### ISSUE TITLE
Li lar orasida 30px joy boliwi kk edi va bg img ning yarmi devorga kirib turishi kerak edi, togirlab qoyamiz 

### ISSUE THREAD

**Issue by FakhriddinovSh** [SayramovAzizbek/Myteam#12]
![image](https://user-images.githubusercontent.com/94530124/177599280-ccb82977-1c78-4826-821b-121d1d0e2181.png)

**Comment by SayramovAzizbek** [comment]
bu yerda jusrify-content:space-between; berilgan edi, margin qilindi
