### ISSUE TITLE
Ikonkalarning hover holati berilmay ketibdi, togirlab qoyamiz ))

### ISSUE THREAD

**Issue by FakhriddinovSh** [SayramovAzizbek/Myteam#13]
![image](https://user-images.githubusercontent.com/94530124/177599359-b47f6ef2-0d98-4c01-a37b-eab3683d0872.png)

**Comment by SayramovAzizbek** [comment]
bular img bo'lin qolgan ekan bularni svg ga o'zgartirildi. Done
