### ISSUE TITLE
Bu rasm joyida qotib turishi kerak edi, to'girlab qoyamiz 

### ISSUE THREAD

**Issue by FakhriddinovSh** [SayramovAzizbek/Myteam#7]
![image](https://user-images.githubusercontent.com/94530124/177598081-7408827e-0861-4b9f-97e8-e3097b0d01d9.png)

**Comment by SayramovAzizbek** [comment]
Bu qilingan edi, lekn px ni oldiga b harifi qo'shilib qolgan ekan, rahmat
