### ISSUE TITLE
3-rasm kornmi qobdi

### ISSUE THREAD

**Issue by FakhriddinovSh** [SayramovAzizbek/Myteam#9]
![image](https://user-images.githubusercontent.com/94530124/177598627-d3f836a0-3595-4f3d-baf0-624328357e1e.png)

**Comment by SayramovAzizbek** [comment]
rasm qo'yilgan, keyinchalik huddi shu rasm oplib kelindi retina bo'lib shunda nomida bitta har o'zgarish bo'lib qolgan ekan
